.TH YTURL 1

.SH NAME
yturl \- get direct URL to YouTube media

.SH SYNOPSIS
.BI yturl " videoid"
[
.I itag
\&... ]

.SH DESCRIPTION
.B yturl
is a simple media URL grabber for YouTube.

.SH ARGUMENTS
.TP
.I videoid
The video ID to get information about. This can also be a URL in a recognised
format. Any official YouTube URL (including one from alternative services like
youtu.be) should be successfully parsed, as well as many more unofficial
services (although these are not guaranteed).
.TP
.I itag
The itag(s) to use. Depending on the number of itags specified, different
format selection methods may be used (see "QUALITY SELECTION").

.SH "QUALITY SELECTION"
If no itags are specified on the command line, yturl will get a URL to the
highest quality format available.

If a single itag is specified on the command line, yturl will attempt to get the
URL to a video in that format, or failing that, as closely resembling that
format as is available.

If multiple itags are specified on the command line, yturl will first try to get
the URL to one of the formats specified on the command line (in order of
arguments). If none of them are available, it will then select the highest
quality video available.

Format quality order is determined by (in order) the maximum video dimensions,
the maximum video bitrate, the maximum audio bitrate and the maximum audio
sample rate.

.SH AUTHORS
Christopher Down <chris at chrisdown dot name>
