.TH YTURL 1
.SH NAME
yturl \- get direct URL to YouTube media
.SH SYNOPSIS
.BI yturl " videoid"
[
.I itag
\&... ]
.SH DESCRIPTION
.B yturl
is a simple media URL grabber for YouTube.
.SH ARGUMENTS
.TP
.I videoid
The video ID to get information about. This can also be a URL in a recognised
format. A URL should be successfully parsed if it contains either
.B v
or
.B video_id
as a POST key present in the URL, or if the link is to
.B youtu.be
or
.BR youtube.com/v/ .
Bear in mind, however, that some URLs will likely have to be escaped or quoted
in your shell to avoid unwanted character interpretation. Please read your
shell's documentation for details on how to handle this (in POSIX shells, use
"..." or '...' as appropriate).
.TP
.I itag
The itag(s) to use. Depending on the number of itags specified, different
format selection methods may be used.

.SH "QUALITY SELECTION"
If no itags are specified on the command line, yturl will get a URL to the
highest quality format available.

If a single itag is specified on the command line, yturl will attempt to get the
URL to a video in that format, or failing that, as closely resembling that
format as is available.

If multiple itags are specified on the command line, yturl will first try to get
the URL to one of the formats specified on the command line (in order of
arguments). If none of them are available, it will then select the highest
quality video available.
.SH "EXIT STATUS"
.TP
.B >4
Successful operation (exit status denotes the itag that was eventually used).
.TP
.B 1
Insufficient arguments, or general Python error.
.TP
.B 2
Invalid video ID.
.TP
.B 3
Invalid itag.
.TP
.B 4
Invalid response from YouTube API.
.SH BUGS
Please report any bugs to https://github.com/cdown/yturl/issues.
.SH COPYRIGHT
Copyright 2011 Christopher Down <iofc.org@christopher.down>.

This is free software; see the COPYING file for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
